## Comp Physio Lab notebook

### Intro to Data Analysis

-   Decided to use R as my primary stats platform instead of prism because I dont care to learn prism and prefer to use this as an opportunity to learn new skills in R

-   it was challenging to convert instructions from prism to R, good resources available for this online

-   L169- One way, **non-parametric** ANOVA used kruskal.test funct.

    \+ add on multi-comparison, Tukey funct. not compatible with kruskal instead used dunn.test function

-   L200- violin plot with box plots and whiskers, first time doing this I had to do some research, used "the R book" and online platforms to build this

    -   main problem is with error bar function I believe this has something to do the the fact that the hybrid cat. only occurs in the ab. tissue.

### Lab 1: Enzyme Activity and Temp

**NOTE FOR METHODS - I have done my best with this data but switched groups between the days and the data from the first data was very inconsistent and I dont trust it. this had a large effect on my ANOVA and if this were a full write up it would be discussed but will not be in the methods of this report however I do recognize the error and its impact.**

Primary questions:

1.  Is there a difference in MHD activity between mussels and crayfish?

2.  Is there a difference in MDH activity at different temperatures?

3.  Does the effect of temperature on MDH activity depend on the specific tissue type?

ASMT: Methods write up

-   import data

-   create box plot in ggplot comparing species and temp

-   run 2way ANOVA

-   calculate Q10

### Lab 2: Insect Metabolism

1.  Sex and Metabolic Rate:

    -   Conduct a t-test to compare metabolic rates between sexes.

    -   Create a boxplot of metabolic rate by sex.

2.  Size and Metabolic Rate:

    -   Perform a log-transformed linear regression of metabolic rate against size.

    -   Generate a scatter plot with a regression line for the log-transformed data.

3.  Sex, Size, and Metabolic Rate:

    -   Run a linear regression with an interaction term between sex and log-transformed size.

    -   Create a scatter plot with separate regression lines for each sex.

4.  Temperature and Metabolic Rate:

    -   Conduct a t-test to compare metabolic rates between two temperature treatments.

    -   Create a boxplot of metabolic rate by temperature.

    -   Calculate the Q10 value for metabolic rate between temperatures.

5.  Sex and Temperature and Metabolic Rate:

    -   Perform a two-way ANOVA to analyze the effects of sex and temperature and their interaction on metabolic rate.

    -   Produce a boxplot or interaction plot to show the combined effects of sex and temperature.

6.  Size and Temperature and Metabolic Rate:

    -   Run a linear regression with interaction between log-transformed size and temperature.

    -   Generate a scatter plot with regression lines for each temperature.

# Lab 3 - Oxidative Stress

Figure 1: Box plot of Catalase activity (I.U. /mg f.w.) by life stage (pupae vs adult) colored by genotype (SK vs VT8)

two way ANOVA w/ 3 Pvalues

-   life stage

-   genotype

-   interaction of LS x Geno
